"""The hand-proved mutation rows: the runner, the census, the retirement check and the pack's reader
interface (SPEC-039 A1 to A11).

A1 to A8 and A10 run the runner against a fixture repository built at run time in a temporary
directory: a git repository with one committed target, one unittest module and, for A8, one crate
with no dependency and its own lockfile, built into the fixture's own `target/`. The fixture's
killers append what they observed to an untracked `observed.log`, so a test can see whether a
killer ran, and against which bytes. A9 reads the committed rows, and A11 plants rows the census
must refuse.
"""

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from _support import REPO, examined

RUNNER = REPO / "scripts" / "mutation_rows.py"
EXAMINED = re.compile(r"^examined (\d+)", re.MULTILINE)
#: The header every fixture carries: the pack's three tables and their declared spellings.
HEADER = {
    "_": [
        "A fixture's rows (SPEC-039).",
        "target spelling: MUTATIONS is crate-relative, crates/{cell 1}/{cell 2}",
        "target spelling: SCRIPT_MUTATIONS is repo-rooted, {cell 1}",
        "target spelling: CARGO_KILLED_SCRIPT_MUTATIONS is repo-rooted, {cell 1}",
    ],
    "arities": {"MUTATIONS": [7], "CARGO_KILLED_SCRIPT_MUTATIONS": [7], "SCRIPT_MUTATIONS": [6]},
    "tables": {"MUTATIONS": [], "CARGO_KILLED_SCRIPT_MUTATIONS": [], "SCRIPT_MUTATIONS": []},
}
TARGET = "scripts/fixmod.py"
TARGET_TEXT = "def double(x):\n    return x * 2\n"
KILLERS = '''"""A fixture's killers; each appends what it observed to observed.log."""

import importlib.util
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("fixmod", ROOT / "scripts" / "fixmod.py")
fixmod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fixmod)


def observe(value):
    with (ROOT / "observed.log").open("a", encoding="utf-8") as log:
        log.write(f"{value}\\n")


class Double(unittest.TestCase):
    def test_two_doubles_to_four(self):
        value = fixmod.double(2)
        observe(value)
        self.assertEqual(value, 4)

    def test_the_result_is_a_whole_number(self):
        value = fixmod.double(3)
        observe(value)
        self.assertIsInstance(value, int)

    def test_red_whatever_the_code(self):
        observe(fixmod.double(2))
        self.assertEqual(fixmod.double(2), 5)
'''
DESCRIPTION = "doubling doubles, not triples"


def script_row(identifier, find, replace, killer, target=TARGET):
    return [identifier, target, find, replace, DESCRIPTION, killer]


def git(root, *args):
    return subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=True
    ).stdout


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


class Fixture:
    """A git repository in a temporary directory, removed when the test ends."""

    def __init__(self, test, rows=(), cargo=False, files=None):
        scratch = tempfile.TemporaryDirectory()
        test.addCleanup(scratch.cleanup)
        self.root = Path(scratch.name)
        self.write("scripts/mutation-rows.json", json.dumps(HEADER, indent=2) + "\n")
        self.write(TARGET, TARGET_TEXT)
        self.write("scripts/tests/test_fixmod.py", KILLERS)
        self.write("README.txt", "a fixture\n")
        self.write(".gitignore", "observed.log\ntarget/\n")
        if cargo:
            self.crate()
        for relative, text in (files or {}).items():
            self.write(relative, text)
        self.rows(rows)
        git(self.root, "init", "-q", "-b", "dev")
        git(self.root, "config", "user.email", "fixture@example.invalid")
        git(self.root, "config", "user.name", "fixture")
        self.commit("the fixture")

    def write(self, relative, text):
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def rows(self, rows, band="S00000-S00099"):
        tables = {"MUTATIONS": [], "CARGO_KILLED_SCRIPT_MUTATIONS": [], "SCRIPT_MUTATIONS": []}
        for table, row in rows:
            tables[table].append(row)
        self.write(f"scripts/mutation-rows.d/{band}.json", json.dumps({"tables": tables}) + "\n")

    def crate(self):
        shutil.copy(REPO / "rust-toolchain.toml", self.root / "rust-toolchain.toml")
        self.write("Cargo.toml", '[workspace]\nmembers = ["crates/fix"]\nresolver = "2"\n')
        self.write(
            "Cargo.lock",
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            'version = 4\n\n[[package]]\nname = "fix"\nversion = "0.1.0"\n',
        )
        self.write(
            "crates/fix/Cargo.toml",
            '[package]\nname = "fix"\nversion = "0.1.0"\nedition = "2021"\n',
        )
        self.write("crates/fix/src/lib.rs", "pub fn double(x: i64) -> i64 {\n    x * 2\n}\n")
        self.write(
            "crates/fix/tests/double.rs",
            "#[test]\nfn two_doubles_to_four() {\n    assert_eq!(fix::double(2), 4);\n}\n\n"
            "#[test]\nfn three_doubles_to_six() {\n    assert_eq!(fix::double(3), 6);\n}\n",
        )

    def commit(self, message):
        git(self.root, "add", "-A")
        git(self.root, "commit", "-q", "-m", message)
        return git(self.root, "rev-parse", "HEAD").strip()

    def run(self, *args, path=None):
        env = {k: v for k, v in os.environ.items() if k != "CARGO_TARGET_DIR"}
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        if path is not None:
            env["PATH"] = path
        return subprocess.run(
            [sys.executable, str(RUNNER), *args, "--root", str(self.root)],
            capture_output=True,
            text=True,
            env=env,
            timeout=3600,
            check=False,
        )

    def observed(self):
        log = self.root / "observed.log"
        return log.read_text(encoding="utf-8").split() if log.is_file() else []

    def report(self):
        """The runner's `--report` file, or no entry when it wrote none."""
        path = self.root / "report.json"
        return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else []


def verdicts(done):
    """{row id: verdict} from the runner's one line per row."""
    found = {}
    for line in done.stdout.splitlines():
        match = re.match(r"^(S\d+-[A-Z0-9-]+): (KILLED|SURVIVED|VOID)\b", line)
        if match:
            found[match.group(1)] = match.group(2)
    return found


class TheRunnerProvesARowTheWayThePackDoes(unittest.TestCase):
    def test_a_tracked_change_is_refused_before_any_mutant_is_installed(self):
        row = script_row(
            "S00001-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        fixture.write("README.txt", "an uncommitted change\n")
        before = sha256(fixture.root / TARGET)
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 2, done.stdout + done.stderr)
        self.assertIn("README.txt", done.stdout + done.stderr)
        self.assertEqual(sha256(fixture.root / TARGET), before)
        self.assertEqual(fixture.observed(), [], "a killer ran on a dirty tree")

    def test_an_anchor_that_does_not_occur_exactly_once_is_void(self):
        row = script_row(
            "S00002-AMBIGUOUS", "x", "y", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00002-AMBIGUOUS": "VOID"})
        self.assertIn("occurs 2 times", done.stdout)
        self.assertEqual(fixture.observed(), [], "a killer ran for an ambiguous anchor")

    def test_a_killer_that_selects_other_than_one_test_is_void(self):
        row = script_row("S00003-TWO-TESTS", "x * 2", "x * 3", "test_fixmod.Double")
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00003-TWO-TESTS": "VOID"})
        self.assertIn("selected 3 tests", done.stdout)

    def test_a_killed_mutant_is_restored_byte_for_byte(self):
        row = script_row(
            "S00004-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00004-DOUBLE": "KILLED"})
        # The control saw the real code double 2, and the mutant made it triple.
        self.assertEqual(fixture.observed(), ["4", "6"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)
        self.assertEqual(git(fixture.root, "status", "--porcelain", "--untracked-files=no"), "")
        self.assertRegex(done.stdout, r"(?m)^examined 1\b")

    def test_a_surviving_mutant_fails_the_run(self):
        row = script_row(
            "S00005-WEAK", "x * 2", "x * 3", "test_fixmod.Double.test_the_result_is_a_whole_number"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00005-WEAK": "SURVIVED"})
        self.assertEqual(fixture.observed(), ["6", "9"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)

    def test_a_mutant_that_does_not_parse_is_void_not_a_kill(self):
        row = script_row(
            "S00006-UNPARSED", "x * 2", "x *", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00006-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        # Only the control ran: the mutant never reached a killer.
        self.assertEqual(fixture.observed(), ["4"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)

    def test_a_killer_red_without_its_mutant_is_void(self):
        row = script_row(
            "S00007-BASE-RED", "x * 2", "x * 3", "test_fixmod.Double.test_red_whatever_the_code"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00007-BASE-RED": "VOID"})
        self.assertIn("fails without its mutant", done.stdout)
        self.assertEqual(fixture.observed(), ["4"], "the killer ran again after its control")

    def test_a_cargo_killer_is_built_first_and_selected_once(self):
        killed = [
            "S00010-CARGO-DOUBLE",
            "fix",
            "src/lib.rs",
            "x * 2",
            "x * 3",
            "double::two_doubles_to_four",
            DESCRIPTION,
        ]
        unbuilt = [
            "S00011-CARGO-UNBUILT",
            "fix",
            "src/lib.rs",
            "x * 2",
            'x * "2"',
            "double::two_doubles_to_four",
            DESCRIPTION,
        ]
        fixture = Fixture(self, [("MUTATIONS", killed), ("MUTATIONS", unbuilt)], cargo=True)
        before = (fixture.root / "crates/fix/src/lib.rs").read_bytes()
        done = fixture.run("prove", "--all", "--report", str(fixture.root / "report.json"))
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(
            verdicts(done), {"S00010-CARGO-DOUBLE": "KILLED", "S00011-CARGO-UNBUILT": "VOID"}
        )
        self.assertIn("does not build", done.stdout)
        report = {entry["id"]: entry for entry in fixture.report()}
        self.assertEqual(report["S00010-CARGO-DOUBLE"]["control"], {"selected": 1, "passed": True})
        self.assertEqual(report["S00010-CARGO-DOUBLE"]["mutant"], {"selected": 1, "passed": False})
        self.assertEqual(report["S00011-CARGO-UNBUILT"]["mutant"], None)
        self.assertEqual((fixture.root / "crates/fix/src/lib.rs").read_bytes(), before)
        self.assertEqual(git(fixture.root, "status", "--porcelain", "--untracked-files=no"), "")


class EveryRowIsCensused(unittest.TestCase):
    def census(self, root):
        return subprocess.run(
            [sys.executable, str(RUNNER), "census", "--root", str(root)],
            capture_output=True,
            text=True,
            timeout=300,
            check=False,
        )

    def test_every_committed_row_is_anchored_once_and_names_one_test(self):
        done = self.census(REPO)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        counts = examined("census reports", EXAMINED.findall(done.stdout))
        self.assertGreater(int(counts[-1]), 0, done.stdout)
        # The census is not blind: a planted ambiguous anchor and a killer naming no test.
        ambiguous = script_row(
            "S00020-AMBIGUOUS", "x", "y", "test_fixmod.Double.test_two_doubles_to_four"
        )
        nameless = script_row("S00021-NAMELESS", "x * 2", "x * 3", "test_fixmod.Double.test_absent")
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", ambiguous), ("SCRIPT_MUTATIONS", nameless)])
        planted = self.census(fixture.root)
        self.assertEqual(planted.returncode, 1, planted.stdout + planted.stderr)
        self.assertIn("S00020-AMBIGUOUS", planted.stdout)
        self.assertIn("occurs 2 times", planted.stdout)
        self.assertIn("S00021-NAMELESS", planted.stdout)
        self.assertIn("names no test", planted.stdout)


class NoRowLeavesWhileItsTargetStays(unittest.TestCase):
    def test_a_row_that_leaves_while_its_target_stays_is_refused(self):
        row = script_row(
            "S00030-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        base = git(fixture.root, "rev-parse", "HEAD").strip()
        fixture.rows([])
        fixture.commit("the row leaves, its target stays")
        refused = fixture.run("retired", "--base", base)
        self.assertEqual(refused.returncode, 1, refused.stdout + refused.stderr)
        self.assertIn("S00030-DOUBLE", refused.stdout)
        self.assertRegex(refused.stdout, r"(?m)^examined 1\b")
        # A retirement record naming the maintainer's approval admits it.
        record = {
            "retired": [
                {
                    "id": "S00030-DOUBLE",
                    "reason": "the fixture's doubling moved into a table-driven test",
                    "approval": "the maintainer, relayed in #1",
                }
            ]
        }
        fixture.write("scripts/mutation-rows.retired.json", json.dumps(record) + "\n")
        fixture.commit("the maintainer approved the retirement")
        admitted = fixture.run("retired", "--base", base)
        self.assertEqual(admitted.returncode, 0, admitted.stdout + admitted.stderr)
        self.assertIn("S00030-DOUBLE", admitted.stdout)
        # A row whose target leaves with it retires on its own.
        gone = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        base = git(gone.root, "rev-parse", "HEAD").strip()
        gone.rows([])
        (gone.root / TARGET).unlink()
        gone.commit("the target and its row leave together")
        alone = gone.run("retired", "--base", base)
        self.assertEqual(alone.returncode, 0, alone.stdout + alone.stderr)
        self.assertIn("S00030-DOUBLE", alone.stdout)


def census(root):
    return subprocess.run(
        [sys.executable, str(RUNNER), "census", "--root", str(root)],
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )


class TheCensusRefusesARowThatCanProveNothing(unittest.TestCase):
    def test_the_census_refuses_a_row_that_can_prove_nothing(self):
        killer = "test_fixmod.Double.test_two_doubles_to_four"
        # A find equal to its replacement installs the unchanged file, and a second row that
        # installs the first row's mutant for the first row's killer adds no evidence.
        same = script_row("S00040-SAME", "x * 2", "x * 2", killer)
        first = script_row("S00041-FIRST", "x * 2", "x * 3", killer)
        again = script_row("S00042-AGAIN", "x * 2", "x * 3", killer)
        rows = [("SCRIPT_MUTATIONS", row) for row in (same, first, again)]
        fixture = Fixture(self, rows)
        refused = census(fixture.root)
        self.assertEqual(refused.returncode, 1, refused.stdout + refused.stderr)
        self.assertIn(
            "census: S00040-SAME: its find is empty or equals its replacement", refused.stdout
        )
        self.assertIn(
            "census: S00042-AGAIN: installs the mutant S00041-FIRST installs, for the same killer",
            refused.stdout,
        )
        self.assertNotIn("S00041-FIRST:", refused.stdout)
        self.assertRegex(refused.stdout, r"(?m)^examined 3 row")
        # A row outside its fragment's band, and an id two fragments hold, stop the census by name.
        outside = Fixture(
            self, [("SCRIPT_MUTATIONS", script_row("S00150-OUT", "x * 2", "x * 3", killer))]
        )
        void = census(outside.root)
        self.assertEqual(void.returncode, 1, void.stdout + void.stderr)
        self.assertIn("S00150-OUT lies outside S0-S99", void.stdout)
        reused = script_row("S00041-FIRST", "x * 2", "x * 5", killer)
        twice = Fixture(self, [("SCRIPT_MUTATIONS", first), ("SCRIPT_MUTATIONS", reused)])
        held = census(twice.root)
        self.assertEqual(held.returncode, 1, held.stdout + held.stderr)
        self.assertIn("the row id S00041-FIRST is held twice", held.stdout)


class TheRunnerProvesEverySelectedRow(unittest.TestCase):
    def test_every_row_its_selectors_name_is_proved_once(self):
        killer = "test_fixmod.Double.test_two_doubles_to_four"
        first = script_row("S00010-DOUBLE", "x * 2", "x * 3", killer)
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", first)])
        second = script_row("S00110-RETURN", "return x * 2", "return x - 2", killer)
        fixture.rows([("SCRIPT_MUTATIONS", second)], band="S00100-S00199")
        fixture.commit("a second band")
        plan = fixture.write("plan.json", json.dumps({"rows": ["S00110-RETURN", "S00010-DOUBLE"]}))
        both = {"S00010-DOUBLE": "KILLED", "S00110-RETURN": "KILLED"}
        for selectors in examined(
            "selector sets",
            [
                ["--band", "S00000-S00099", "--row", "S00110-RETURN"],
                ["--band", "S00100-S00199", "--rows-from", str(plan)],
                ["--row", "S00010-DOUBLE", "--row", "S00110-RETURN", "--row", "S00010-DOUBLE"],
            ],
        ):
            done = fixture.run("prove", *selectors)
            self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
            self.assertEqual(verdicts(done), both, " ".join(selectors))
            self.assertRegex(done.stdout, r"(?m)^examined 2\b", " ".join(selectors))


#: A bash script that uses an array, which `sh -n` refuses and `bash -n` accepts, and prints 3.
BASH_TARGET = "scripts/fixtool.sh"
BASH_TEXT = "#!/usr/bin/env bash\na=(1 2)\necho $(( ${a[0]} + ${a[1]} ))\n"
#: The same, kept by its shebang alone: no `.sh` or `.bash` extension.
BASH_SHEBANG_TARGET = "scripts/fixtool"
#: A POSIX script that prints 3.
SH_TARGET = "scripts/fixposix.sh"
SH_TEXT = "#!/bin/sh\necho $((1 + 2))\n"
#: Opens an `if` no `fi` closes, so neither shell reads the file.
UNPARSED = ("echo $((", "if echo $((")
TOOL_KILLERS = '''"""A fixture's shell killers; each appends what it observed to observed.log."""

import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def observe(value):
    with (ROOT / "observed.log").open("a", encoding="utf-8") as log:
        log.write(f"{value}\\n")


def printed(shell, script):
    done = subprocess.run(
        [shell, str(ROOT / script)], capture_output=True, text=True, check=False
    )
    value = done.stdout.strip() or "nothing"
    observe(value)
    return value


class Tool(unittest.TestCase):
    def test_bash_sums_to_three(self):
        self.assertEqual(printed("bash", "scripts/fixtool.sh"), "3")

    def test_bash_shebang_sums_to_three(self):
        self.assertEqual(printed("bash", "scripts/fixtool"), "3")

    def test_sh_sums_to_three(self):
        self.assertEqual(printed("sh", "scripts/fixposix.sh"), "3")

    def test_bash_by_path_sums_to_three(self):
        self.assertEqual(printed("/bin/bash", "scripts/fixtool.sh"), "3")

    def test_marker_sums_to_three(self):
        self.assertEqual(printed("sh", "scripts/fixmark.sh"), "3")

    def test_extension_bash_sums_to_three(self):
        self.assertEqual(printed("bash", "scripts/fixext.bash"), "3")

    def test_extension_sh_sums_to_three(self):
        self.assertEqual(printed("sh", "scripts/fixext.sh"), "3")

    def test_dash_sums_to_three(self):
        self.assertEqual(printed("sh", "scripts/fixdash"), "3")
'''
#: Targets with no shebang: only the extension says which shell reads them.
EXT_BASH_TARGET = "scripts/fixext.bash"
EXT_BASH_TEXT = "a=(1 2)\necho $(( ${a[0]} + ${a[1]} ))\n"
EXT_SH_TARGET = "scripts/fixext.sh"
EXT_SH_TEXT = "echo $((1 + 2))\n"
#: A target whose shebang names dash and which has no extension.
DASH_TARGET = "scripts/fixdash"
DASH_TEXT = "#!/bin/dash\necho $((1 + 2))\n"
#: A construct `bash -n` reads and `sh -n` does not, in place of a sum.
ARRAY_MUTANT = ("echo $((1 + 2))", "a=(1 2); echo 3")
MARK_TARGET = "scripts/fixmark.sh"
TOOL_FILES = {
    EXT_BASH_TARGET: EXT_BASH_TEXT,
    EXT_SH_TARGET: EXT_SH_TEXT,
    DASH_TARGET: DASH_TEXT,
    BASH_TARGET: BASH_TEXT,
    BASH_SHEBANG_TARGET: BASH_TEXT,
    SH_TARGET: SH_TEXT,
    "scripts/tests/test_fixtool.py": TOOL_KILLERS,
}


def runner_module():
    """The runner imported as a module, for the tests that call `parses` and `builds` directly."""
    scripts = str(REPO / "scripts")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    import mutation_rows

    return mutation_rows


class TheRunnerParseChecksAShellMutant(unittest.TestCase):
    """SPEC-039 A41: a shell target's mutant is parse-checked, `bash -n` for a bash script and
    `sh -n` otherwise; one that fails is VOID, never a kill."""

    def prove(self, row):
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)], files=TOOL_FILES)
        target = fixture.root / row[1]
        before = target.read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(target.read_bytes(), before, "the target was not restored")
        return fixture, done

    def test_the_fixture_construct_parses_under_bash_and_not_under_sh(self):
        script = Path(tempfile.mkdtemp()) / "array.sh"
        self.addCleanup(shutil.rmtree, script.parent)
        script.write_text(BASH_TEXT, encoding="utf-8")
        bash = subprocess.run(["bash", "-n", str(script)], capture_output=True, text=True)
        posix = subprocess.run(["sh", "-n", str(script)], capture_output=True, text=True)
        self.assertEqual(bash.returncode, 0, bash.stderr)
        self.assertNotEqual(
            posix.returncode, 0, "sh reads the array, so the fixture proves nothing"
        )
        self.assertRegex(posix.stderr, r"(?i)syntax error")

    def test_a_bash_mutant_that_does_not_parse_is_void_not_a_kill(self):
        row = script_row(
            "S00020-BASH-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_bash_sums_to_three",
            target=BASH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00020-BASH-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertIn("bash", done.stdout)
        # Only the control ran: the mutant never reached its killer.
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_bash_mutant_refused_with_exit_one_is_void(self):
        # `bash -n` exits 1, not 2, on an array assignment left open at the end of its input.
        row = script_row(
            "S00034-BASH-OPEN-ARRAY",
            "a=(1 2)",
            "a=(1 2",
            "test_fixtool.Tool.test_bash_sums_to_three",
            target=BASH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00034-BASH-OPEN-ARRAY": "VOID"})
        self.assertIn("unexpected EOF while looking for matching", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_bash_mutant_that_parses_and_is_caught_is_killed(self):
        row = script_row(
            "S00021-BASH-CAUGHT",
            "+ ${a[1]}",
            "* ${a[1]}",
            "test_fixtool.Tool.test_bash_sums_to_three",
            target=BASH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00021-BASH-CAUGHT": "KILLED"})
        # The control read 1 + 2, and the mutant read 1 * 2: both ran.
        self.assertEqual(fixture.observed(), ["3", "2"])

    def test_a_shebang_alone_makes_a_target_a_shell_script(self):
        row = script_row(
            "S00022-SHEBANG-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_bash_shebang_sums_to_three",
            target=BASH_SHEBANG_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00022-SHEBANG-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_posix_sh_mutant_that_does_not_parse_is_void_not_a_kill(self):
        row = script_row(
            "S00023-SH-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_sh_sums_to_three",
            target=SH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00023-SH-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_posix_sh_mutant_that_parses_and_is_caught_is_killed(self):
        row = script_row(
            "S00024-SH-CAUGHT",
            "1 + 2",
            "1 * 2",
            "test_fixtool.Tool.test_sh_sums_to_three",
            target=SH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00024-SH-CAUGHT": "KILLED"})
        self.assertEqual(fixture.observed(), ["3", "2"])

    def test_a_bash_only_mutant_of_an_sh_shebang_script_is_void(self):
        row = script_row(
            "S00025-SH-SHEBANG-BASHISM",
            *ARRAY_MUTANT,
            "test_fixtool.Tool.test_sh_sums_to_three",
            target=SH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00025-SH-SHEBANG-BASHISM": "VOID"})
        self.assertIn("sh: ", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_bash_extension_with_no_shebang_is_read_by_bash(self):
        caught = script_row(
            "S00026-BASH-EXT-CAUGHT",
            "+ ${a[1]}",
            "* ${a[1]}",
            "test_fixtool.Tool.test_extension_bash_sums_to_three",
            target=EXT_BASH_TARGET,
        )
        fixture, done = self.prove(caught)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00026-BASH-EXT-CAUGHT": "KILLED"})
        self.assertEqual(fixture.observed(), ["3", "2"])

    def test_a_bash_extension_mutant_that_does_not_parse_is_void(self):
        row = script_row(
            "S00027-BASH-EXT-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_extension_bash_sums_to_three",
            target=EXT_BASH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00027-BASH-EXT-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_an_sh_extension_with_no_shebang_is_read_by_sh(self):
        row = script_row(
            "S00028-SH-EXT-BASHISM",
            *ARRAY_MUTANT,
            "test_fixtool.Tool.test_extension_sh_sums_to_three",
            target=EXT_SH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00028-SH-EXT-BASHISM": "VOID"})
        self.assertIn("sh: ", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_an_sh_extension_mutant_that_does_not_parse_is_void(self):
        row = script_row(
            "S00029-SH-EXT-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_extension_sh_sums_to_three",
            target=EXT_SH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00029-SH-EXT-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_a_dash_shebang_makes_a_target_a_shell_script(self):
        row = script_row(
            "S00030-DASH-UNPARSED",
            *UNPARSED,
            "test_fixtool.Tool.test_dash_sums_to_three",
            target=DASH_TARGET,
        )
        fixture, done = self.prove(row)
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00030-DASH-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        self.assertEqual(fixture.observed(), ["3"])

    def test_the_parse_check_reads_the_mutant_and_never_runs_it(self):
        marker = "echo MARK >> {}/observed.log\n"
        row = script_row(
            "S00031-MARKED",
            "1 + 2",
            "1 * 2",
            "test_fixtool.Tool.test_marker_sums_to_three",
            target=MARK_TARGET,
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)], files=TOOL_FILES)
        fixture.write(
            MARK_TARGET, "#!/bin/sh\n" + marker.format(fixture.root) + "echo $((1 + 2))\n"
        )
        fixture.commit("a target that marks each execution")
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00031-MARKED": "KILLED"})
        # The control run and the killer run each executed the target once; the parse check
        # executed nothing, so no third mark exists.
        self.assertEqual(fixture.observed(), ["MARK", "3", "MARK", "2"])

    def test_a_missing_parser_leaves_the_mutant_unchecked_and_void(self):
        row = script_row(
            "S00032-NO-PARSER",
            "+ ${a[1]}",
            "* ${a[1]}",
            "test_fixtool.Tool.test_bash_by_path_sums_to_three",
            target=BASH_TARGET,
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)], files=TOOL_FILES)
        bare = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, bare)
        (bare / "git").symlink_to(shutil.which("git"))
        # The killer runs /bin/bash by path, so only the runner's own lookup meets the bare PATH.
        control = fixture.run("prove", "--all")
        self.assertEqual(verdicts(control), {"S00032-NO-PARSER": "KILLED"}, control.stdout)
        done = fixture.run("prove", "--all", path=str(bare))
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00032-NO-PARSER": "VOID"})
        self.assertIn("unchecked: bash is not installed", done.stdout)

    def test_a_parser_that_hangs_leaves_the_mutant_unchecked_and_void(self):
        runner = runner_module()
        stubs = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, stubs)
        stub = stubs / "bash"
        stub.write_text("#!/bin/sh\nexec sleep 30\n", encoding="utf-8")
        stub.chmod(0o755)
        with (
            mock.patch.dict(os.environ, {"PATH": f"{stubs}:/usr/bin:/bin"}),
            mock.patch.object(runner, "PARSE_SECONDS", 1),
        ):
            why = runner.parses("bash", b"echo 1\n")
        self.assertEqual(why, "the mutant is unchecked: bash -n timed out")
        with mock.patch.dict(os.environ, {"PATH": str(stubs / "none")}):
            why = runner.parses("bash", b"echo 1\n")
        self.assertEqual(why, "the mutant is unchecked: bash is not installed")

    def test_the_reason_is_the_first_line_of_a_two_line_refusal(self):
        runner = runner_module()
        why = runner.parses("bash", b"if then\n")
        self.assertEqual(
            why,
            "the mutant does not parse: bash: bash: line 1: syntax error near unexpected token"
            " `then'",
        )

    def test_a_shell_target_with_a_cargo_killer_is_parsed_first_and_built_second(self):
        runner = runner_module()
        row = runner.Row("S00033-CARGO-SHELL", "SCRIPT", "scripts/x.sh", "a", "b", "k", None, "d")
        killer = runner.Killer("cargo", "t", "crates/f/tests/t.rs", "fix", "t")
        text = b"#!/usr/bin/env bash\necho 1\n"
        calls = []

        def record(command, **_):
            calls.append(command)
            return subprocess.CompletedProcess(command, 0, b"", b"")

        with mock.patch.object(runner.subprocess, "run", side_effect=record):
            self.assertIsNone(runner.builds(Path("."), row, killer, text))
        self.assertEqual([call[0] for call in calls], ["bash", "cargo"])
        self.assertEqual(calls[0], ["bash", "-n"])
        self.assertEqual(calls[1][1:3], ["test", "--locked"])
        self.assertIn("--no-run", calls[1])

        calls.clear()

        def refuse(command, **_):
            calls.append(command)
            return subprocess.CompletedProcess(command, 2, b"", b"bash: line 1: bad\n")

        with mock.patch.object(runner.subprocess, "run", side_effect=refuse):
            why = runner.builds(Path("."), row, killer, text)
        self.assertEqual(why, "the mutant does not parse: bash: bash: line 1: bad")
        self.assertEqual(calls, [["bash", "-n"]], "an unparsed mutant must never reach cargo")

    def test_a_target_that_is_not_a_shell_script_is_given_no_parser(self):
        runner = runner_module()
        self.assertIsNone(runner.shell_parser("crates/f/src/lib.rs", b"fn main() {}\n"))
        self.assertIsNone(runner.shell_parser("db/001.sql", b"select 1;\n"))
        # The control: the same call names a parser once the target is a shell script.
        self.assertEqual(runner.shell_parser("scripts/x.sh", b"select 1;\n"), "sh")


BIN_MANIFEST = (
    '[package]\nname = "fix"\nversion = "0.1.0"\nedition = "2021"\n\n'
    '[[bin]]\nname = "fixbin"\npath = "src/main.rs"\n'
)
#: A crate with a library and one binary, the binary named other than the package, with a unit test
#: in its root file and one in a module it declares; the library holds a test the binary does not.
BIN_FILES = {
    "crates/fix/Cargo.toml": BIN_MANIFEST,
    "crates/fix/src/lib.rs": (
        "pub fn double(x: i64) -> i64 {\n    x * 2\n}\n\n"
        "#[cfg(test)]\nmod tests {\n    #[test]\n    fn only_in_the_lib() {\n"
        "        assert_eq!(super::double(2), 4);\n    }\n}\n"
    ),
    "crates/fix/src/main.rs": (
        "mod helper;\n\nfn triple(x: i64) -> i64 {\n    x * 3\n}\n\n"
        'fn main() {\n    println!("{}", triple(2) + helper::halve(4));\n}\n\n'
        "#[cfg(test)]\nmod tests {\n    #[test]\n    fn three_triples_to_nine() {\n"
        "        assert_eq!(super::triple(3), 9);\n    }\n}\n"
    ),
    "crates/fix/src/helper.rs": (
        "pub fn halve(x: i64) -> i64 {\n    x / 2\n}\n\n"
        "#[cfg(test)]\nmod tests {\n    #[test]\n    fn four_halves_to_two() {\n"
        "        assert_eq!(super::halve(4), 2);\n    }\n}\n"
    ),
}
BIN_KILLER = "bin::tests::three_triples_to_nine"


def bin_row(identifier, killer, find="x * 3", replace="x * 4", path="src/main.rs"):
    return (
        "MUTATIONS",
        [identifier, "fix", path, find, replace, killer, DESCRIPTION],
    )


class TheBinKillerRunsTheBinarysOwnUnitTests(unittest.TestCase):
    """SPEC-039 A42 to A44 (issue #352): a killer `bin::<test path>` names one unit test of the
    crate's binary, resolved against the binary's own sources and run with `--bin`."""

    def located(self, fixture, index=0):
        runner = runner_module()
        rows = runner.rows_of(runner.load_tree(fixture.root))
        try:
            return runner, rows[index], runner.locate_killer(fixture.root, rows[index])
        except runner.KillerUnresolved as refusal:
            self.fail(f"a bin killer is refused: {refusal}")

    def test_a_bin_killer_runs_cargo_test_on_the_binary_by_its_exact_path(self):
        fixture = Fixture(self, [bin_row("S00050-BIN", BIN_KILLER)], cargo=True, files=BIN_FILES)
        runner, row, killer = self.located(fixture)
        self.assertEqual((killer.package, killer.binary), ("fix", "fixbin"))
        calls = []

        def record(command, **kwargs):
            calls.append((command, kwargs["cwd"]))
            return subprocess.CompletedProcess(command, 0, "running 1 test\n", "")

        with mock.patch.object(runner.subprocess, "run", side_effect=record):
            run = runner.run_killer(fixture.root, killer, Path("."))
            self.assertIsNone(runner.builds(fixture.root, row, killer, b"x"))
        self.assertEqual((run.selected, run.passed), (1, True))
        self.assertEqual(
            calls[0][0],
            ["cargo", "test", "--locked", "-p", "fix", "--bin", "fixbin"]
            + ["--", "--exact", "tests::three_triples_to_nine"],
        )
        self.assertEqual(
            calls[1][0],
            ["cargo", "test", "--locked", "-p", "fix", "--bin", "fixbin", "--no-run"],
        )
        self.assertEqual(calls[0][1], fixture.root)

    def test_a_bin_killers_binary_is_read_from_its_manifest_and_never_guessed(self):
        fixture = Fixture(self, [bin_row("S00051-BIN", BIN_KILLER)], cargo=True, files=BIN_FILES)
        self.assertEqual(self.located(fixture)[2].binary, "fixbin")
        # No [[bin]] table: the binary is the package's own, named by the package.
        plain = Fixture(
            self,
            [bin_row("S00052-BIN", BIN_KILLER)],
            cargo=True,
            files=dict(BIN_FILES, **{"crates/fix/Cargo.toml": BIN_MANIFEST.split("\n[[bin]]")[0]}),
        )
        self.assertEqual(self.located(plain)[2].binary, "fix")
        # Two binaries: the killer names none of them, so it is refused, not guessed.
        two = Fixture(
            self,
            [bin_row("S00053-BIN", BIN_KILLER)],
            cargo=True,
            files=dict(
                BIN_FILES,
                **{
                    "crates/fix/Cargo.toml": BIN_MANIFEST
                    + '\n[[bin]]\nname = "other"\npath = "src/other.rs"\n'
                },
            ),
        )
        runner = runner_module()
        with self.assertRaisesRegex(runner.KillerUnresolved, "2 binaries"):
            runner.locate_killer(two.root, runner.rows_of(runner.load_tree(two.root))[0])

    def test_a_bin_killer_that_selects_no_test_is_void_and_never_killed(self):
        rows = [
            bin_row("S00054-BIN-KILLED", BIN_KILLER),
            bin_row("S00055-BIN-NO-TEST", "bin::tests::no_such_test", replace="x * 5"),
        ]
        fixture = Fixture(self, rows, cargo=True, files=BIN_FILES)
        before = (fixture.root / "crates/fix/src/main.rs").read_bytes()
        done = fixture.run("prove", "--all", "--report", str(fixture.root / "report.json"))
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(
            verdicts(done), {"S00054-BIN-KILLED": "KILLED", "S00055-BIN-NO-TEST": "VOID"}
        )
        self.assertIn("selected 0 tests, not one", done.stdout)
        report = {entry["id"]: entry for entry in fixture.report()}
        self.assertEqual(report["S00054-BIN-KILLED"]["mutant"], {"selected": 1, "passed": False})
        # The plant that selects nothing never reached its mutant: only the control ran.
        self.assertIsNone(report["S00055-BIN-NO-TEST"]["mutant"])
        self.assertEqual((fixture.root / "crates/fix/src/main.rs").read_bytes(), before)

    def test_a_bin_killer_outside_the_binarys_sources_is_refused_by_the_census(self):
        rows = [
            bin_row("S00056-BIN-ROOT", BIN_KILLER),
            bin_row(
                "S00057-BIN-MODULE",
                "bin::helper::tests::four_halves_to_two",
                find="x / 2",
                replace="x / 3",
                path="src/helper.rs",
            ),
            bin_row(
                "S00058-BIN-LIB-TEST",
                "bin::tests::only_in_the_lib",
                find="x * 2",
                replace="x * 5",
                path="src/lib.rs",
            ),
        ]
        fixture = Fixture(self, rows, cargo=True, files=BIN_FILES)
        done = census(fixture.root)
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn(
            "census: S00058-BIN-LIB-TEST: its killer bin::tests::only_in_the_lib names no test: "
            "crates/fix/src/main.rs declares only_in_the_lib 0 times",
            done.stdout,
        )
        # The two killers the binary holds, one in its root file and one in a module it declares,
        # resolve: they are not named.
        self.assertNotIn("S00056", done.stdout)
        self.assertNotIn("S00057", done.stdout)
        self.assertRegex(done.stdout, r"(?m)^examined 3 row")


class TheBinKillerFollowsRustcAndRefusesAShadow(unittest.TestCase):
    """The verifier's plants (v) and (vi) for SPEC-039 section 15: a binary's root named other than
    `main.rs` declares its modules beside itself, as rustc reads a crate root; and a crate whose
    `tests/bin.rs` the `bin` kind shadows is refused, never rerouted to the binary's own test."""

    def test_a_module_beside_a_root_not_named_main_resolves(self):
        manifest = BIN_MANIFEST.replace('path = "src/main.rs"', 'path = "src/other.rs"')
        files = {
            "crates/fix/Cargo.toml": manifest,
            "crates/fix/src/other.rs": "mod helper;\n\nfn main() {}\n",
            "crates/fix/src/helper.rs": BIN_FILES["crates/fix/src/helper.rs"],
        }
        rows = [
            bin_row(
                "S00059-BIN-OTHER-ROOT-MODULE",
                "bin::helper::tests::four_halves_to_two",
                find="x / 2",
                replace="x / 3",
                path="src/helper.rs",
            )
        ]
        fixture = Fixture(self, rows, cargo=True, files=files)
        done = census(fixture.root)
        self.assertNotIn("S00059", done.stdout)
        self.assertRegex(done.stdout, r"(?m)^examined 1 row")

    def test_a_bin_killer_beside_a_tests_bin_rs_is_refused(self):
        files = dict(
            BIN_FILES,
            **{
                "crates/fix/tests/bin.rs": (
                    "#[cfg(test)]\nmod tests {\n    #[test]\n    fn three_triples_to_nine() {\n"
                    "        assert_eq!(9, 9);\n    }\n}\n"
                )
            },
        )
        fixture = Fixture(self, [bin_row("S00060-BIN-SHADOW", BIN_KILLER)], cargo=True, files=files)
        done = census(fixture.root)
        self.assertIn(
            "census: S00060-BIN-SHADOW: its killer bin::tests::three_triples_to_nine crates/fix "
            "has a test target bin, which the bin kind shadows",
            done.stdout,
        )
        self.assertRegex(done.stdout, r"(?m)^examined 1 row")


if __name__ == "__main__":
    unittest.main()
