"""The hand-proved mutation rows: the runner, the census, the retirement check and the pack's reader
interface (SPEC-039 A1 to A11).

A1 to A8 and A10 run the runner against a fixture repository built at run time in a temporary
directory: a git repository with one committed target, one unittest module and, for A8, one crate
with no dependency and its own lockfile, built into the fixture's own `target/`. The fixture's
killers append what they observed to an untracked `observed.log`, so a test can see whether a
killer ran, and against which bytes. A9 and A11 read the committed rows.
"""

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from _support import REPO, examined

RUNNER = REPO / "scripts" / "mutation_rows.py"
PROBE = REPO / ".packs" / "scripts" / "mutation-probe.py"
EXAMINED = re.compile(r"^examined (\d+)", re.MULTILINE)
#: The header every fixture carries: the pack's three tables and their declared spellings.
HEADER = {
    "_": [
        "A fixture's rows (SPEC-039).",
        "target spelling: MUTATIONS is crate-relative, crates/{cell 1}/{cell 2}",
        "target spelling: SCRIPT_MUTATIONS is repo-rooted, {cell 1}",
        "target spelling: CARGO_KILLED_SCRIPT_MUTATIONS is repo-rooted, {cell 1}",
    ],
    "arities": {"MUTATIONS": [7], "CARGO_KILLED_SCRIPT_MUTATIONS": [7], "SCRIPT_MUTATIONS": [6]},
    "tables": {"MUTATIONS": [], "CARGO_KILLED_SCRIPT_MUTATIONS": [], "SCRIPT_MUTATIONS": []},
}
TARGET = "scripts/fixmod.py"
TARGET_TEXT = "def double(x):\n    return x * 2\n"
KILLERS = '''"""A fixture's killers; each appends what it observed to observed.log."""

import importlib.util
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("fixmod", ROOT / "scripts" / "fixmod.py")
fixmod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fixmod)


def observe(value):
    with (ROOT / "observed.log").open("a", encoding="utf-8") as log:
        log.write(f"{value}\\n")


class Double(unittest.TestCase):
    def test_two_doubles_to_four(self):
        value = fixmod.double(2)
        observe(value)
        self.assertEqual(value, 4)

    def test_the_result_is_a_whole_number(self):
        value = fixmod.double(3)
        observe(value)
        self.assertIsInstance(value, int)

    def test_red_whatever_the_code(self):
        observe(fixmod.double(2))
        self.assertEqual(fixmod.double(2), 5)
'''
DESCRIPTION = "doubling doubles, not triples"


def script_row(identifier, find, replace, killer):
    return [identifier, TARGET, find, replace, DESCRIPTION, killer]


def git(root, *args):
    return subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=True
    ).stdout


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


class Fixture:
    """A git repository in a temporary directory, removed when the test ends."""

    def __init__(self, test, rows=(), cargo=False):
        scratch = tempfile.TemporaryDirectory()
        test.addCleanup(scratch.cleanup)
        self.root = Path(scratch.name)
        self.write("scripts/mutation-rows.json", json.dumps(HEADER, indent=2) + "\n")
        self.write(TARGET, TARGET_TEXT)
        self.write("scripts/tests/test_fixmod.py", KILLERS)
        self.write("README.txt", "a fixture\n")
        self.write(".gitignore", "observed.log\ntarget/\n")
        if cargo:
            self.crate()
        self.rows(rows)
        git(self.root, "init", "-q", "-b", "dev")
        git(self.root, "config", "user.email", "fixture@example.invalid")
        git(self.root, "config", "user.name", "fixture")
        self.commit("the fixture")

    def write(self, relative, text):
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def rows(self, rows, band="S00000-S00099"):
        tables = {"MUTATIONS": [], "CARGO_KILLED_SCRIPT_MUTATIONS": [], "SCRIPT_MUTATIONS": []}
        for table, row in rows:
            tables[table].append(row)
        self.write(f"scripts/mutation-rows.d/{band}.json", json.dumps({"tables": tables}) + "\n")

    def crate(self):
        shutil.copy(REPO / "rust-toolchain.toml", self.root / "rust-toolchain.toml")
        self.write("Cargo.toml", '[workspace]\nmembers = ["crates/fix"]\nresolver = "2"\n')
        self.write(
            "Cargo.lock",
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            'version = 4\n\n[[package]]\nname = "fix"\nversion = "0.1.0"\n',
        )
        self.write(
            "crates/fix/Cargo.toml",
            '[package]\nname = "fix"\nversion = "0.1.0"\nedition = "2021"\n',
        )
        self.write("crates/fix/src/lib.rs", "pub fn double(x: i64) -> i64 {\n    x * 2\n}\n")
        self.write(
            "crates/fix/tests/double.rs",
            "#[test]\nfn two_doubles_to_four() {\n    assert_eq!(fix::double(2), 4);\n}\n\n"
            "#[test]\nfn three_doubles_to_six() {\n    assert_eq!(fix::double(3), 6);\n}\n",
        )

    def commit(self, message):
        git(self.root, "add", "-A")
        git(self.root, "commit", "-q", "-m", message)
        return git(self.root, "rev-parse", "HEAD").strip()

    def run(self, *args):
        env = {k: v for k, v in os.environ.items() if k != "CARGO_TARGET_DIR"}
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        return subprocess.run(
            [sys.executable, str(RUNNER), *args, "--root", str(self.root)],
            capture_output=True,
            text=True,
            env=env,
            timeout=3600,
            check=False,
        )

    def observed(self):
        log = self.root / "observed.log"
        return log.read_text(encoding="utf-8").split() if log.is_file() else []

    def report(self):
        """The runner's `--report` file, or no entry when it wrote none."""
        path = self.root / "report.json"
        return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else []


def verdicts(done):
    """{row id: verdict} from the runner's one line per row."""
    found = {}
    for line in done.stdout.splitlines():
        match = re.match(r"^(S\d+-[A-Z0-9-]+): (KILLED|SURVIVED|VOID)\b", line)
        if match:
            found[match.group(1)] = match.group(2)
    return found


class TheRunnerProvesARowTheWayThePackDoes(unittest.TestCase):
    def test_a_tracked_change_is_refused_before_any_mutant_is_installed(self):
        row = script_row(
            "S00001-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        fixture.write("README.txt", "an uncommitted change\n")
        before = sha256(fixture.root / TARGET)
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 2, done.stdout + done.stderr)
        self.assertIn("README.txt", done.stdout + done.stderr)
        self.assertEqual(sha256(fixture.root / TARGET), before)
        self.assertEqual(fixture.observed(), [], "a killer ran on a dirty tree")

    def test_an_anchor_that_does_not_occur_exactly_once_is_void(self):
        row = script_row(
            "S00002-AMBIGUOUS", "x", "y", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00002-AMBIGUOUS": "VOID"})
        self.assertIn("occurs 2 times", done.stdout)
        self.assertEqual(fixture.observed(), [], "a killer ran for an ambiguous anchor")

    def test_a_killer_that_selects_other_than_one_test_is_void(self):
        row = script_row("S00003-TWO-TESTS", "x * 2", "x * 3", "test_fixmod.Double")
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00003-TWO-TESTS": "VOID"})
        self.assertIn("selected 3 tests", done.stdout)

    def test_a_killed_mutant_is_restored_byte_for_byte(self):
        row = script_row(
            "S00004-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00004-DOUBLE": "KILLED"})
        # The control saw the real code double 2, and the mutant made it triple.
        self.assertEqual(fixture.observed(), ["4", "6"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)
        self.assertEqual(git(fixture.root, "status", "--porcelain", "--untracked-files=no"), "")
        self.assertRegex(done.stdout, r"(?m)^examined 1\b")

    def test_a_surviving_mutant_fails_the_run(self):
        row = script_row(
            "S00005-WEAK", "x * 2", "x * 3", "test_fixmod.Double.test_the_result_is_a_whole_number"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00005-WEAK": "SURVIVED"})
        self.assertEqual(fixture.observed(), ["6", "9"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)

    def test_a_mutant_that_does_not_parse_is_void_not_a_kill(self):
        row = script_row(
            "S00006-UNPARSED", "x * 2", "x *", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        before = (fixture.root / TARGET).read_bytes()
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00006-UNPARSED": "VOID"})
        self.assertIn("does not parse", done.stdout)
        # Only the control ran: the mutant never reached a killer.
        self.assertEqual(fixture.observed(), ["4"])
        self.assertEqual((fixture.root / TARGET).read_bytes(), before)

    def test_a_killer_red_without_its_mutant_is_void(self):
        row = script_row(
            "S00007-BASE-RED", "x * 2", "x * 3", "test_fixmod.Double.test_red_whatever_the_code"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        done = fixture.run("prove", "--all")
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(verdicts(done), {"S00007-BASE-RED": "VOID"})
        self.assertIn("fails without its mutant", done.stdout)
        self.assertEqual(fixture.observed(), ["4"], "the killer ran again after its control")

    def test_a_cargo_killer_is_built_first_and_selected_once(self):
        killed = [
            "S00010-CARGO-DOUBLE",
            "fix",
            "src/lib.rs",
            "x * 2",
            "x * 3",
            "double::two_doubles_to_four",
            DESCRIPTION,
        ]
        unbuilt = [
            "S00011-CARGO-UNBUILT",
            "fix",
            "src/lib.rs",
            "x * 2",
            'x * "2"',
            "double::two_doubles_to_four",
            DESCRIPTION,
        ]
        fixture = Fixture(self, [("MUTATIONS", killed), ("MUTATIONS", unbuilt)], cargo=True)
        before = (fixture.root / "crates/fix/src/lib.rs").read_bytes()
        done = fixture.run("prove", "--all", "--report", str(fixture.root / "report.json"))
        self.assertEqual(done.returncode, 3, done.stdout + done.stderr)
        self.assertEqual(
            verdicts(done), {"S00010-CARGO-DOUBLE": "KILLED", "S00011-CARGO-UNBUILT": "VOID"}
        )
        self.assertIn("does not build", done.stdout)
        report = {entry["id"]: entry for entry in fixture.report()}
        self.assertEqual(report["S00010-CARGO-DOUBLE"]["control"], {"selected": 1, "passed": True})
        self.assertEqual(report["S00010-CARGO-DOUBLE"]["mutant"], {"selected": 1, "passed": False})
        self.assertEqual(report["S00011-CARGO-UNBUILT"]["mutant"], None)
        self.assertEqual((fixture.root / "crates/fix/src/lib.rs").read_bytes(), before)
        self.assertEqual(git(fixture.root, "status", "--porcelain", "--untracked-files=no"), "")


class EveryRowIsCensused(unittest.TestCase):
    def census(self, root):
        return subprocess.run(
            [sys.executable, str(RUNNER), "census", "--root", str(root)],
            capture_output=True,
            text=True,
            timeout=300,
            check=False,
        )

    def test_every_committed_row_is_anchored_once_and_names_one_test(self):
        done = self.census(REPO)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        counts = examined("census reports", EXAMINED.findall(done.stdout))
        self.assertGreater(int(counts[-1]), 0, done.stdout)
        # The census is not blind: a planted ambiguous anchor and a killer naming no test.
        ambiguous = script_row(
            "S00020-AMBIGUOUS", "x", "y", "test_fixmod.Double.test_two_doubles_to_four"
        )
        nameless = script_row("S00021-NAMELESS", "x * 2", "x * 3", "test_fixmod.Double.test_absent")
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", ambiguous), ("SCRIPT_MUTATIONS", nameless)])
        planted = self.census(fixture.root)
        self.assertEqual(planted.returncode, 1, planted.stdout + planted.stderr)
        self.assertIn("S00020-AMBIGUOUS", planted.stdout)
        self.assertIn("occurs 2 times", planted.stdout)
        self.assertIn("S00021-NAMELESS", planted.stdout)
        self.assertIn("names no test", planted.stdout)


class NoRowLeavesWhileItsTargetStays(unittest.TestCase):
    def test_a_row_that_leaves_while_its_target_stays_is_refused(self):
        row = script_row(
            "S00030-DOUBLE", "x * 2", "x * 3", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        base = git(fixture.root, "rev-parse", "HEAD").strip()
        fixture.rows([])
        fixture.commit("the row leaves, its target stays")
        refused = fixture.run("retired", "--base", base)
        self.assertEqual(refused.returncode, 1, refused.stdout + refused.stderr)
        self.assertIn("S00030-DOUBLE", refused.stdout)
        self.assertRegex(refused.stdout, r"(?m)^examined 1\b")
        # A retirement record naming the maintainer's approval admits it.
        record = {
            "retired": [
                {
                    "id": "S00030-DOUBLE",
                    "reason": "the fixture's doubling moved into a table-driven test",
                    "approval": "the maintainer, relayed in #1",
                }
            ]
        }
        fixture.write("scripts/mutation-rows.retired.json", json.dumps(record) + "\n")
        fixture.commit("the maintainer approved the retirement")
        admitted = fixture.run("retired", "--base", base)
        self.assertEqual(admitted.returncode, 0, admitted.stdout + admitted.stderr)
        self.assertIn("S00030-DOUBLE", admitted.stdout)
        # A row whose target leaves with it retires on its own.
        gone = Fixture(self, [("SCRIPT_MUTATIONS", row)])
        base = git(gone.root, "rev-parse", "HEAD").strip()
        gone.rows([])
        (gone.root / TARGET).unlink()
        gone.commit("the target and its row leave together")
        alone = gone.run("retired", "--base", base)
        self.assertEqual(alone.returncode, 0, alone.stdout + alone.stderr)
        self.assertIn("S00030-DOUBLE", alone.stdout)


def probe(root, klass):
    return subprocess.run(
        [sys.executable, str(PROBE), "--root", str(root), "check", klass],
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )


class ThePacksProbeReadsTheRows(unittest.TestCase):
    def test_the_vendored_probe_judges_the_rows_through_the_reader(self):
        for klass in examined("row classes", ["find-differs", "band-ids", "mutants-distinct"]):
            done = probe(REPO, klass)
            self.assertEqual(done.returncode, 0, f"{klass}: {done.stdout}{done.stderr}")
            counts = EXAMINED.findall(done.stdout)
            self.assertTrue(counts and int(counts[-1]) > 0, f"{klass}: {done.stdout}")
        # Through the reader, a planted row whose find equals its replacement is refused by name.
        same = script_row(
            "S00040-SAME", "x * 2", "x * 2", "test_fixmod.Double.test_two_doubles_to_four"
        )
        fixture = Fixture(self, [("SCRIPT_MUTATIONS", same)])
        shutil.copy(REPO / "scripts" / "mutation_rows.py", fixture.root / "scripts")
        shutil.copy(REPO / "scripts" / "row_target.py", fixture.root / "scripts")
        planted = probe(fixture.root, "find-differs")
        self.assertEqual(planted.returncode, 1, planted.stdout + planted.stderr)
        self.assertIn("S00040-SAME", planted.stdout)


if __name__ == "__main__":
    unittest.main()
